version: '3.8'

services:
  psql:
    image: postgres:latest
    container_name: billify
    environment:
      POSTGRES_DB: billify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: